import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import { TriggerProvider } from "@trigger.dev/react";
import Navbar from "@/components/navbar";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <ClerkProvider signInUrl="/sign-in" signUpUrl="/sign-up">
        <TriggerProvider
          publicApiKey={process.env.NEXT_PUBLIC_TRIGGER_PUBLIC_API_KEY!}
        >
          <body
            className={cn(
              "min-h-screen bg-background font-sans antialiased relative",
              fontSans.variable
            )}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              disableTransitionOnChange
            >
              <div className="bg-grid"></div>
              <Navbar />
              {children}
              <Footer />
              <Toaster />
            </ThemeProvider>
          </body>
        </TriggerProvider>
      </ClerkProvider>
    </html>
  );
}
